#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=nnUNet_setup
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2022.05

cd ai4mi_project

source ai4mi/bin/activate

export nnUNet_raw="/home/scur2494/ai4mi_project/nnUNet/nnUNet_raw"
export nnUNet_preprocessed="/home/scur2494/ai4mi_project/nnUNet/nnUNet_preprocessed"
export nnUNet_results="/home/scur2494/ai4mi_project/nnUNet/nnUNet_results"

#replace with your home directory before running.

git clone https://github.com/MIC-DKFZ/nnUNet.git

cd nnUNet

pip install -e .

mkdir nnUNet_results
mkdir nnUNet_preprocessed

cd ..

python nnUnet_transform_data.py --data_dir 'data/segthor_train' --nnUNet_raw 'nnUNet/nnUNet_raw' --nnUNet_preprocessed 'nnUNet/nnUNet_preprocessed'

cd nnUNet

nnUNetv2_plan_and_preprocess -d 001 --verify_dataset_integrity 

cp -f /home/scur2494/ai4mi_project/nnUNet_Mods/evaluate_predictions.py /home/scur2494/ai4mi_project/nnUNet/nnunetv2/evaluation/evaluate_predictions.py
cp -f /home/scur2494/ai4mi_project/nnUNet_Mods/nnUNetPlans.json /home/scur2494/ai4mi_project/nnUNet/nnUNet_preprocessed/Dataset001_SegTHOR/nnUNetPlans.json
cp -f /home/scur2494/ai4mi_project/nnUNet_Mods/nnUNetTrainer.py /home/scur2494/ai4mi_project/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py
cp -f /home/scur2494/ai4mi_project/nnUNet_Mods/run_training.py /home/scur2494/ai4mi_project/nnUNet/nnunetv2/run/run_training.py
