#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=nnUNet_setup
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2022.05

cd ai4mi_project

source ai4mi/bin/activate

export nnUNet_raw="/home/scur2494/ai4mi_project/nnUNet/nnUNet_raw"
export nnUNet_preprocessed="/home/scur2494/ai4mi_project/nnUNet/nnUNet_preprocessed"
export nnUNet_results="/home/scur2494/ai4mi_project/nnUNet/nnUNet_results"

#replace with your home directory before running.

nnUNetv2_train 1 2d 1
python plot_dice_nnUNet --file '/home/scur2494/ai4mi_project/nnUNet/nnUNet_results/Dataset001_SegTHOR/nnUNetTrainer__nnUNetPlans__2d/fold_1/training_log_2024_10_15_15_54_21.txt' --dest '/home/scur2494/ai4mi_project/nnUNet/nnUNet_results/Dataset001_SegTHOR/nnUNetTrainer__nnUNetPlans__2d/dice.png' 
#2D version

nnUNetv2_train 1 3d_fullres 1
#3d_fullres version

nnUNetv2_train 1 3d_lowres 1
#3d_lowres version
